const countries = [
  {
    id: 1,
    name: 'Angola',
    iso: 'AO',
    code: '+244',
    cities: [
      'Luanda',
      'Cabinda',
      'Huambo',
      'Lubango',
      "N'dalatando",
      'Soyo',
      'Uíge',
      'Benguela',
    ],
  },
  {
    id: 2,
    name: 'Benin',
    iso: 'BJ',
    code: '+229',
    cities: [
      'Cotonou',
      'Abomey-Calavi',
      'Djougou',
      'Porto-Novo',
      'Parakou',
      'Bohicon',
      'Kandi',
    ],
  },
  {
    id: 3,
    name: 'Burkina Faso',
    iso: 'BF',
    code: '+226',
    cities: [
      'Ouagadougou',
      'Bobo-Dioulasso',
      'Koudougou',
      'Ouahigouya',
      'Banfora',
      'Dédougou',
      'Kaya',
    ],
  },

  {
    id: 4,
    name: 'Burundi',
    iso: 'BI',
    code: '+257',
    cities: ['Bujumbura', 'Muyinga', 'Gitega', 'Ruyigi', 'Ngozi', 'Mouila'],
  },
  {
    id: 5,
    name: 'Central African Republic',
    iso: 'CF',
    code: '+236',
    cities: [
      'Bangui',
      'Bimbo',
      'Mbaïki',
      'Berbérati',
      'Kaga-Bandoro',
      'Bozoum',
    ],
    },
    {
        id: 6,
        name: 'Chad',
        iso: 'TD',
        code: '+235',
        cities: [
            'NDjamena',
            'Moundou',
            'Sarh',
        ],
    },
  {
    id: 7,
    name: 'RD Congo',
    iso: 'CD',
    code: '+243',
    cities: [
      'Kinshasa',
      'Lubumbashi',
      'Mbuji-Mayi',
      'Kisangani',
      'Masina',
      'Kananga',
      'Likasi',
      'Kolwezi',
      'Tshikapa',
      'Beni',
      'Bukavu',
      'Mwene-Ditu',
    ],
  },
  {
    id: 8,
    name: 'Congo Republic',
    iso: 'CG',
    code: '+242',
    cities: [
      'Brazzaville',
      'Pointe-Noire',
      'Dolisie',
      'Kayes',
      'Owando',
      'Ouésso',
    ],
  },
  {
    id: 9,
    name: 'Cameroun',
    iso: 'CM',
    code: '+237',
    cities: [
      'Douala',
      'Yaoundé',
      'Garoua',
      'Kousséri',
      'Bamenda',
      'Maroua',
      'Bafoussam',
      'Mokolo',
      'Ngaoundéré',
      'Bertoua',
      'Edéa',
      'Loum',
      'Limbe',
      'Buea',
      'Kribi',
      'Ebolowa',
      'Sangmelima',
      'Mbalmayo',
      'Bafia',
      'Eseka',
      'Mutenguene',
      'Mbanga',
      'Soa',
    ],
  },
  {
    id: 10,
    name: "Cote d'ivoire",
    iso: 'CI',
    code: '+225',
    cities: [
      'Abidjan',
      'Abobo',
      'Bouaké',
      'Daloa',
      'Man',
      'Yamoussoukro',
      'Abengourou',
      'Gagnoa',
      'Korhogo',
      'San-Pédro',
      'Divo',
      'Anyama',
    ],
  },
  {
    id: 11,
    name: 'Ethiopia',
    iso: 'ET',
    code: '+251',
    cities: [
      'Addis Ababa',
      'Dire Dawa',
      "Mek'ele",
      'Nazret',
      'Bahir Dar',
      'Gonder',
      'Dessie',
      'Awasa',
      'Jimma',
      'Bishoftu',
      'Kombolcha',
      'Harar',
    ],
  },
  {
    id: 12,
    name: 'Gabon',
    iso: 'GA',
    code: '+241',
    cities: [
      'Libreville',
      'Port-Gentil',
      'Franceville',
      'Oyem',
      'Moanda',
      'Mouila',
      'Lambaréné',
      'Tchibanga',
      'Koulamoutou',
      'Makokou',
    ],
  },

  {
    id: 13,
    name: 'Ghana',
    iso: 'GH',
    code: '+233',
    cities: [
      'Accra',
      'Kumasi',
      'Tamale',
      'Takoradze',
      'Achiaman',
      'Tema',
      'Cape Coast',
      'Sekondi-Takoradi',
      'Obuase',
      'Medina Estates',
      'Koforidua',
      'Japekrom',
    ],
  },
  {
    id: 14,
    name: 'Guinea',
    iso: 'GN',
    code: '+224',
    cities: [
      'Camayenne',
      'Conakry',
      'Nzérékoré',
      'Kindia',
      'Kankan',
      'Gueckedou',
      'Coyah',
      'Labé',
      'Kissidougou',
      'Fria',
      'Siguiri',
      'Macenta',
    ],
  },
  {
    id: 15,
    name: 'Kenya',
    iso: 'KE',
    code: '+254',
    cities: [
      'Nairobi',
      'Nakuru',
      'Mombasa',
      'Eldoret',
      'Kisumu',
      'Thika',
      'Malindi',
      'Kitale',
      'Garissa',
      'Kakamega',
      'Kapenguria',
      'Bungoma',
    ],
  },
  {
    id: 16,
    name: 'Madagascar',
    iso: 'MG',
    code: '+261',
    cities: [
      'Antananarivo',
      'Toamasina',
      'Antsirabe',
      'Fianarantsoa',
      'Mahajanga',
      'Toliara',
      'Antsiranana',
      'Antanifotsy',
      'Ambovombe',
      'Ambilobe',
      'Amparafaravola',
      'Tôlanaro',
    ],
  },
  {
    id: 17,
    name: 'Mali',
    iso: 'ML',
    code: '+223',
    cities: [
      'Bamako',
      'Sikasso',
      'Mopti',
      'Koutiala',
      'Ségou',
      'Gao',
      'Kayes',
      'Markala',
      'Kolokani',
      'Kati',
      'Bougouni',
      'Tombouctou',
    ],
  },
  {
    id: 18,
    name: 'Niger',
    iso: 'NE',
    code: '+227',
    cities: [
      'Niamey',
      'Zinder',
      'Maradi',
      'Agadez',
      'Alaghsas',
      'Tahoua',
      'Dosso',
      'Birni N Konni',
      'Tessaoua',
      'Gaya',
      'Dogondoutchi',
      'Diffa',
    ],
  },
  {
    id: 19,
    name: 'Nigeria',
    iso: 'NG',
    code: '+234',
    cities: [
      'Abuja',
      'Lagos',
      'Kano',
      'Ibadan',
      'Kaduna',
      'Port Harcourt',
      'Benin City',
      'Maiduguri',
      'Zaria',
      'Aba',
      'Jos',
      'Ilorin',
      'Oyo',
    ],
  },
  {
    id: 20,
    name: 'Rwanda',
    iso: 'RW',
    code: '+250',
    cities: [
      'Kigali',
      'Butare',
      'Gitarama',
      'Ruhengeri',
      'Gisenyi',
      'Byumba',
      'Cyangugu',
      'Kibuye',
      'Rwamagana',
      'Kibungo',
      'Nzega',
    ],
  },
  {
    id: 21,
    name: 'Senegal',
    iso: 'SN',
    code: '+221',
    cities: [
      'Dakar',
      'Pikine',
      'Touba',
      'Thiès',
      'Thiès Nones',
      'Saint-Louis',
      'Kaolack',
      'Ziguinchor',
      'Tiébo',
      'Tambacounda',
      'Mbaké',
      'Louga',
    ],
  },

  {
    id: 22,
    name: 'South Africa',
    iso: 'ZA',
    code: '+27',
    cities: [
      'Cape Town',
      'Durban',
      'Johannesburg',
      'Soweto',
      'Pretoria',
      'Port Elizabeth',
      'Pietermaritzburg',
      'Benoni',
      'Tembisa',
      'East London',
      'Vereeniging',
      'Bloemfontein',
    ],
  },
  {
    id: 23,
    name: 'Tanzania',
    iso: 'TZ',
    code: '+255',
    cities: [
      'Dar es Salaam',
      'Mwanza',
      'Zanzibar',
      'Arusha',
      'Mbeya',
      'Morogoro',
      'Tanga',
      'Dodoma',
      'Kigoma',
      'Moshi',
      'Tabora',
      'Songea',
    ],
  },
  {
    id: 24,
    name: 'Togo',
    iso: 'TG',
    code: '+228',
    cities: [
      'Lomé',
      'Sokodé',
      'Kara',
      'Atakpamé',
      'Palimé',
      'Bassar',
      'Tsévié',
      'Aného',
      'Sansanné-Mango',
      'Dapaong',
      'Tchamba',
      'Badou',
    ],
  },

  {
    id: 25,
    name: 'Uganda',
    iso: 'UG',
    code: '+256',
    cities: [
      'Kampala',
      'Gulu',
      'Lira',
      'Mbarara',
      'Jinja',
      'Bwizibwera',
      'Mbale',
      'Mukono',
      'Kasese',
      'Masaka',
      'Entebbe',
      'Njeru',
    ],
  },
  {
    id: 26,
    name: 'Zambia',
    iso: 'ZM',
    code: '+260',
    cities: [
      'Lusaka',
      'Kitwe',
      'Ndola',
      'Kabwe',
      'Chingola',
      'Mufulira',
      'Luanshya',
      'Livingstone',
      'Kasama',
      'Chipata',
      'Kalulushi',
      'Mazabuka',
    ],
  },
];

export default countries;
